name: AgendaHOF

options:
  bundleIdPrefix: com.agendahof
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""
    PRODUCT_BUNDLE_IDENTIFIER: com.agendahof.swift
    TARGETED_DEVICE_FAMILY: "1,2"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_PREVIEWS: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    INFOPLIST_FILE: Info.plist
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    SWIFT_EMIT_LOC_STRINGS: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_ASSET_PATHS: "\"Preview Content\""

targets:
  AgendaHOF:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - "**/*.xcodeproj"
          - "**/*.xcworkspace"
          - ".git/**"
          - ".build/**"
          - "DerivedData/**"
          - "**/*.sh"
          - "project.yml"
          - "Package.swift"
          - "**/*.md"
          - ".DS_Store"
          - "Preview Content/**"
          - "Assets.xcassets/**"
        createIntermediateGroups: true
      - path: Assets.xcassets
        type: folder
      - path: Preview Content
        type: folder
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.agendahof.swift
        PRODUCT_NAME: "$(TARGET_NAME)"
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: supabase-swift
        products:
          - Supabase

packages:
  supabase-swift:
    url: https://github.com/supabase/supabase-swift.git
    from: 2.0.0

schemes:
  AgendaHOF:
    build:
      targets:
        AgendaHOF: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
